### ISSUE TITLE
Duda significado tarea En el apartado 1  (pag 2 fichero Proyecto_2021) 

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/communities_and_crime_machine_learning#6]
En el apartado 1  (pag 2 fichero Proyecto_2021) no sé qué quiere que hagamso cuando dice 
enfoque elegido

```
1. Definición del problema a resolver y enfoque elegido. Identifique el uso de los datos en el ajuste y valoración de resultados
```

Este es el enunciado.

**Comment by alejbormeg** [comment]
Eso lo entiendo como que expliques brevemente la estrategia que vamos a seguir para resolverlo.

Pero vaya no se si es eso exactamente
