### ISSUE TITLE
Mediar con el los datos no balanceados de regresión

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/communities_and_crime_machine_learning#7]
Las clases no balanceadas es un problema de clasificación ¿para regresión no se hace nada?
Las opciones que tenemos son:   
- No hacer nada para remediarlo mencionarlo en la memoria ¿esto causará peor ajuste que si fuera homogéneo? ¿cómo influye?
- Preguntarle al profesor qué hacer.

**Comment by alejbormeg** [comment]
Yo viendo las gráficas que ayer pusiste por el grupo diría que lo mejor es preguntar al profesor, sineramente yo creo que lo mejor sería simplemente mezclar los datos y separarlos en test y train como siempre.

**Comment by BlancaCC** [comment]
Dijo Nicolás que en regresión no se aplican
